name: kyan
description: A new Flutter project.

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #FLUTTER LOCAL NOTIFICATIONS
  flutter_local_notifications: ^9.6.0

  #TIME ZONE
  timezone: ^0.8.0

  #STATE MANAGEMENTS
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+2
  provider: ^6.0.3

  #JSON
  retrofit: ^3.0.1+1
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0

  #IMAGE
  cached_network_image: ^3.2.1

  #PIN CODE
  pin_code_fields: ^7.4.0

  #GG SIGN IN
  google_sign_in: ^5.3.3

  #CALENDAR
  syncfusion_flutter_datepicker: ^20.1.60

  #CALENDAR TIME LINE
  calendar_timeline: ^1.0.4

  #SOCKET IO
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

  #SNIPPET CODER
  snippet_coder_utils: ^1.0.12

  #INTRO SCREEN
  introduction_screen: ^3.0.2

  #URL LAUNCHER
  url_launcher: ^6.1.3

  #INTL
  intl_utils: ^2.6.1

  #MY PACKGAE
  coder0211: ^0.0.72

  #ANIMATED SEARCH BOX
  anim_search_bar: ^2.0.2
  month_picker_dialog: ^0.4.0
  flutter_ringtone_player: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/res/icons/icon_logo_app.png"
  #flutter pub run flutter_launcher_icons:main

  #Dart Analysis
  lint: ^1.8.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/res/images/
    - lib/res/icons/
