on:
  push:
    tags:
      - "v*.*.*"
name: Build and Release apk
jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - name: Read FLUTTER_VERSION
        id: get-version
        run: echo "::set-output name=version::$(cat FLUTTER_VERSION)"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ steps.get-version.outputs.version }}
      - run: flutter pub get
      - run: flutter build apk
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.TOKEN }}
